site_name: Rewards Sharing Simulation Engine for Ethereum - Docs
nav:
        - Home: index.md
        - Configuration: configuration.md
        - Stakeholder profiles: stakeholders.md
        - Metrics: metrics.md
        - Examples: examples.md
        
theme: gitbook
plugins: []